config/routes.rb
Blog1::Application.routes.draw do

  resources :posts do 
    resources :comments
  end

  resources :users

  get "login" => "sessions#new"
  post "login" => "sessions#create"
  delete "logout" => "sessions#destroy"
  get "logout" => "sessions#destroy"
  
  get "about" => "site#about"
  get "contact" => "site#contact"
  get "privacy" => "site#privacy"
  get "terms" => "site#terms"

  root to: "site#index"
end

app/models/comment.rb
class Comment
	include MongoMapper::Document

	key :commenter, String
	key :body, String

  belongs_to :post
end

app/models/post.rb
class Post
	include MongoMapper::Document

	key :title, String 
	key :text, String

	has_many :comments, dependent: :destroy
	validates :title, presence: true,
						length: { minimum: 5 }	
	
end

app/models/user.rb
class User
  include MongoMapper::Document

  before_save :encrypt_password
  
  attr_accessor :password, :password_confirmation

  key :email, String
  key :salt, String
  key :fish, String
  key :code, String

  def self.authenticate(email, password)
    user = User.find_by_email(email)
    
    if user
      fish = BCrypt::Engine.hash_secret(password, user.salt)
      if user.fish == fish
        return user
      end
    end
    nil
  end

  
  private
  
  def validate_confirmation
    unless password == password_confirmation
      errors.add( :password_confirmation, "Passwords do not match.")
    end
  end
  
  def encrypt_password
    unless password.blank?
      self.salt = BCrypt::Engine.generate_salt
      self.fish = BCrypt::Engine.hash_secret(password, self.salt)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
 
  def current_user
    @current_user ||= User.find(session[:user_id])
  end
  
  def is_authenticated
    redirect_to login_url unless current_user
  end

  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	
	http_basic_authenticate_with name: 'dhh', password: 'secret', only: :destroy

	def create
		@post = Post.find(params[:post_id])
		@comment = @post.comments.create(params[:comment])			
		redirect_to post_path(@post)
	end

	def destroy
		@post = Post.find(params[:post_id])
		@comment = @post.comments.find(params[:id])
		@comment.destroy
		redirect_to post_path(@post)
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

	http_basic_authenticate_with name: 'ray', password: '123', except: [:index,]

	def index
		@posts = Post.all
	end # snipped for brevity

	def new
		@post = Post.new
	end

	def create
		@post = Post.new(params[:post].permit(:title, :text))

		if @post.save
			redirect_to @post
		else
			render 'new'
		end
	end
	
	def show
		@post = Post.find(params[:id])
	end

	def edit
		@post = Post.find(params[:id])
	end

	def update
		@post = Post.find(params[:id])

		if @post.update(params[:post].permit(:title, :text))
			redirect_to @post
		else
			render 'edit'
		end
	end

	def destroy
		@post = Post.find(params[:id])
		@post.destroy

		redirect_to posts_path
	end
 
	private
		def post_params
			params.require(:post).permit(:title, :text)
		end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

def new 
	render 'signin/index'
end

  def create
  	
    if params[:user][:password].blank?


      user = User.where(params[:user].permit(:email)).first
      
      if user
        user.code = SecureRandom.urlsafe_base64
        user.expires_at = Time.now + 4.hours
        user.save
        
        # # Send the password reset email with the coded link
        # PasswordMailer.reset_email(user).deliver
      end

      render 'signin/index'
    else
      user = User.authenticate(params[:user][:email], params[:user][:password])
      
      if user
        session[:user_id] = user.id
        redirect_to root_url, notice: "You've successfully logged in!"
      else
        render 'signin/index'
      end
    end
  end

end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  
  def index
  end
  
  def about
  end
  
  def contact
  end
  
  def privacy
  end
  
  def terms
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

before_action :is_authenticated, only: [ :index, :show ]
  def index
    @users = User.all
  end

  def show
    @user = User.find params[:id]
  end

  def new
    @user = User.new
  end

  def create
    @user = User.create user_params
    
    if @user
      redirect_to users_path, status: 303
    else
      render :new
    end
  end

 private
  
  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/views/comments/_comment.html.erb
<p>
	<strong>Commenter:</strong>
	<%= comment.commenter %>
</p>

<p>
	<strong>Comment:</strong>
	<%= comment.body %>
</p>

<p>
	<%= link_to 'Destroy Comment', [comment.post, comment],
				method: :delete,
				data: { confirm: 'Are you sure you want to delete this?' } %>
</p>

app/views/comments/_form.html.erb
<%= form_for([@post, @post.comments.build]) do |f| %>
	<p>
		<%= f.label :commenter %><br>
		<%= f.text_field :commenter %>
	</p>
	<p>
		<%= f.label :body %><br>
		<%= f.text_area :body %>
	</p>
	<p>
		<%= f.submit %>
	</p>
<% end %>

app/views/layouts/_footer.html.erb
<div class="container">

  <!-- FOOTER -->
  <footer>
    <p class="pull-right"><a href="#">Back to top</a></p>
    <p>
      &copy; 2013 StanceTrader, Inc. &middot;
      <%= link_to 'Privacy', privacy_path %> &middot;
      <%= link_to 'Terms of Use', terms_path %>
    </p>
  </footer>

</div>

app/views/layouts/_navigation.html.erb
<div class="navbar-wrapper">
  <div class="container">
    <div class="navbar navbar-inverse navbar-static-top">
      <div class="container">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
        <%= link_to "StanceTrader", root_url, class: "navbar-brand" %>
        <div class="nav-collapse collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to 'Home', root_path %></li>
            <li><%= link_to 'About', about_path %></li>
            <li><%= link_to 'Contact', contact_path %></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Car Parts</title>
    
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render partial: "layouts/navigation" %>
    <%= render partial: "site/carousel" %>
    <div class="container">
      <%= yield %>
    </div>
    <%= render partial: "layouts/footer" %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
	<% if @post.errors.any? %>
	<div id="errorExplanation">
		<h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>
		<ul>
		<% @post.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
		<% end %>
		</ul>
	</div>
	<% end %>
	<p>
		<%= f.label :title %><br>
		<%= f.text_field :title %>
	</p>

	<p>
		<%= f.label :text %><br>
		<%= f.text_area :text %>
	</p>
		
	<p>
		<%= f.submit %>
	 b </p>
<% end %>

app/views/posts/edit.html.erb
<h1>This is where we edit the form</h1>

<%= form_for :post, url: post_path(@post.id), method: :patch do |f| %>
	<% if @post.errors.any? %>
	<div id="errorExplanation">
		<h2><%= pluralize(@post.errors.count, "error") %>prohibited this post from being saved:</h2>
		<ul>
		<% @post.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
		<% end %>
		</ul>
	</div>
	<% end %> 
	<p>
		<%= f.label :title %><br>
		<%= f.text_field :title %>
	</p>

	<p>
		<%= f.label :text %><br>
		<%= f.text_area :text %>
	</p>

	<p>
		<%= f.submit %>
	</p>
<% end %>

<%= link_to 'Back back it uuupppp', posts_path %> 

app/views/posts/index.html.erb
<h1>What's up!</h1><br/>
<h2>This is the StanceTrader Car Parts page</h2>
<br>
	
<%= link_to 'New post', new_post_path %>
<br>
<br>
<table>
	<tr>
		<th>Name of Car Parts</th>
		<th>Car Parts Description</th>
		<th></th>
		<th></th>
	</tr>

	<% @posts.each do |post| %>
		<tr>
			<td><%= post.title %></td>
			<td><%= post.text %></td>
			<td><%= link_to 'Show', post_path(post)%></td> <!-- (post) is an argument for post_path -->
			<td><%= link_to 'Edit', edit_post_path(post) %></td>
			<td><%= link_to 'Destroy', post_path(post), method: :delete, data: { confirm: 'You sure you wanna delete this?' } %></td>
		</tr>
	<% end %>
</table>
<br>
<b><%= link_to 'Homepage', root_path %></b>

app/views/posts/new.html.erb
<h1>StanceTrader</h1><br>
<h2>Post your awesome car parts here!</h2>

<%= form_for :post, url: posts_path do |f| %>
	<% if @post.errors.any? %>
	<div id='errorExplanation'>5
		<h2><%= pluralize(@post.errors.count, 'error') %> prohibited this post from being saved:</h2>
		<ul>
			<% @post.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
			<% end %>
		</ul>
	</div>
	<% end %>
	<p>
		<%= f.label :title %><br>
		<%= f.text_field :title %>
	</p>
	<p>
		<%= f.label :text %><br>
		<%= f.text_area :text %>
	</p>
	<p>
		<%= f.submit %>
	</p>
<% end %>

<%= link_to 'Back back it upppp', posts_path %>

app/views/posts/show.html.erb
<p>
	<strong><h1>Title:</h1></strong>
	<%= @post.title %>
</p>

<p>
	<strong><h2>Text:</h2></strong>
	<%= @post.text %>
</p>

<h4>Comments</h4>
<%= render @post.comments %>

<h4>Add your comments here.</h4>
<%= render 'comments/form' %>

<%= link_to 'Back to the Car Parts page', posts_path %>
<%= link_to 'Edit', edit_post_path(@post) %>

app/views/signin/index.html.erb
<!-- <!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Signin Template for Bootstrap</title> -->

    <!-- Bootstrap core CSS -->
    <!-- <link href="../bootstrap/css/bootstrap.css" rel="stylesheet"> -->

    <!-- Custom styles for this template --><!-- 
    <link href="../assests/signin.css?body=1" rel="stylesheet"> -->
<!--   </head>

  <body>
 -->
    <div class="container">

    <%= form_for :user, url: "/login", method: "post" do |f| %>
      <p><%= f.label :email %> 
      <%= f.text_field :email %>
      </p>
      <p>
       <%= f.label :password %>
      <%= f.text_field :password %>
      </p>
      <%= f.submit %>
      <% end %>

<!-- 
      <form action="/login"  method="post"class="form-signin">
        <h3 class="form-signin-heading">StanceTrader Signin</h3>
        <input type="text" class="form-control" placeholder="Email address" autofocus>
        <input type="password" class="form-control" placeholder="Password">
        <label class="checkbox">
          <input type="checkbox" value="remember-me"> Remember me
        </label>
         <%= token_tag form_authenticity_token %>
        <button class="btn btn-large btn-primary btn-block" type="submit">Sign in</button>

      </form>
 -->
    </div> <!-- /container -->
<!-- 
  </body>
</html> -->

app/views/site/_carousel.html.erb
<!-- Carousel ================================================== -->
<div id="myCarousel" class="carousel slide">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
    <li data-target="#myCarousel" data-slide-to="1"></li>
    <li data-target="#myCarousel" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner">
    <div class="item active">
      <img src="https://sphotos-b.xx.fbcdn.net/hphotos-ash3/1098007_548906675157118_2116206366_n.png" alt="">
      <div class="container">
        <div class="carousel-caption">
          <h1>StanceTrader</h1>
          <p>Buy well. Sell well. Discover. </p>
          <p><%= link_to 'Sign up today', new_user_path, class: "btn btn-large btn-primary" %></p>
        </div>
      </div>
    </div>
    <div class="item">
      <img src="https://sphotos-a-pao.xx.fbcdn.net/hphotos-prn1/564643_548213845226401_1356367265_n.png" alt="">
      <div class="container">
        <div class="carousel-caption">
          <h1>Seamless marketplace.</h1>
          <p>It's easy to list and find your car parts on StanceTrader.</p>
          <p><a class="btn btn-large btn-primary" href="#">Learn more</a></p>
        </div>
      </div>
    </div>
    <div class="item">
      <img src="https://sphotos-a-pao.xx.fbcdn.net/hphotos-ash3/1148851_548213695226416_1012975967_n.png" alt="">
      <div class="container">
        <div class="carousel-caption">
          <h1>Exciting.</h1>
          <p>Cool story bro.</p>
          <p><a class="btn btn-large btn-primary" href="#">Browse gallery</a></p>
        </div>
      </div>
    </div>
  </div>
  <a class="left carousel-control" href="#myCarousel" data-slide="prev"><span class="glyphicon glyphicon-chevron-left"></span></a>
  <a class="right carousel-control" href="#myCarousel" data-slide="next"><span class="glyphicon glyphicon-chevron-right"></span></a>
</div><!-- /.carousel -->

app/views/site/about.html.erb
<h1>StanceTrader is built by gearheads for gearheads</h1>

<h2>Who we are and what we're all about</h2>	

<p>Hey there, Stancin' all day errday</p>

<b><%= link_to 'Homepage', root_path %></b>

app/views/site/contact.html.erb
<h1>Holler @ us here</h1>

<h2> Contact</h2> 

<h3>
		<tr>email: admin@stancetrader.com</tr><br>
		<tr>twitter: @stancetrader</tr><br>
		<tr>fb: fb.com/stancetrader</tr><br>
</h3><br>

<b><%= link_to 'Homepage', root_path %></b>

app/views/site/index.html.erb
<!-- Marketing messaging and featurettes
================================================== -->
<!-- Wrap the rest of the page in another container to center all the content. -->

<div class="marketing">
  <!-- Three columns of text below the carousel -->
  <div class="row">
    <div class="col-lg-4">
      <img class="img-circle" src="https://fbcdn-profile-a.akamaihd.net/hprofile-ak-prn2/c99.1.621.621/s160x160/181396_10152824319480284_1912078816_n.jpg">
      <h2>Buy.</h2>
      <p>Step your car game up by buying baller car parts for the car show, race season, drifting, and the streets.</p>
      <p><%= link_to 'Post & List Now &raquo;'.html_safe, posts_path, class: "btn btn-default"%></p>
    </div><!-- /.col-lg-4 -->
    <div class="col-lg-4">
      <img class="img-circle" src="http://upload.wikimedia.org/wikipedia/commons/thumb/b/be/Lot007.jpg/240px-Lot007.jpg">
      <h2>Sell.</h2>
      <p>Looking to sell your car parts from racing, car shows, or drifting? This is the place to be.</p>
      <p><%= link_to 'Post & List Now &raquo;' .html_safe, posts_path, class: "btn btn-default" %></p>
    </div><!-- /.col-lg-4 -->
    <div class="col-lg-4">
      <img class="img-circle" src="http://upload.wikimedia.org/wikipedia/commons/thumb/c/cb/Limited_Edition.jpg/220px-Limited_Edition.jpg">
      <h2>Discover.</h2>
      <p>Just rolling by? We curate car parts that you may be interested in. The place to be for hot-rodders.</p>
      <p><%= link_to 'Post & List Now &raquo;' .html_safe, posts_path, class: 'btn btn-default' %></p>
    </div><!-- /.col-lg-4 -->
  </div><!-- /.row -->


  <!-- START THE FEATURETTES -->

  <hr class="featurette-divider">

  <div class="featurette">
    <img class="featurette-image img-circle pull-right" img src="https://fbcdn-sphotos-a-a.akamaihd.net/hphotos-ak-ash3/p480x480/1148973_545506238830495_244804096_n.jpg">
    <h2 class="featurette-heading">Because you want to search for car parts seamlessly. <span class="text-muted">It'll blow your mind.</span></h2>
    <p class="lead">Discover car parts that you're looking for from local enthusiasts.</p>
  </div>

  <hr class="featurette-divider">

  <div class="featurette">
    <img class="featurette-image img-circle pull-left" src="https://fbcdn-sphotos-b-a.akamaihd.net/hphotos-ak-prn2/217616_460280767353043_1127587875_n.jpg">
    <h2 class="featurette-heading">Enthusiast marketplace. <span class="text-muted">See for yourself.</span></h2>
    <p class="lead">We're more than a marketplace. Connect with fellow enthusiasts who share the same passion.</p>
  </div>

  <hr class="featurette-divider">

  <div class="featurette">
    <img class="featurette-image img-circle pull-right" img src="http://aussieexotics.com/forum/dlattach/attach,15874/image/Top-Gear-(UK)/Darth-Vader-Ariel-Atom-1821.0.html.jpg">
    <h2 class="featurette-heading">And lastly, this one. <span class="text-muted">BAM!</span></h2>
    <p class="lead">Sign up or else Darth Vader will roll up in his Ariel Atom and find you.</p>
  </div>

  <hr class="featurette-divider">

  <!-- /END THE FEATURETTES -->
</div><!-- /.container -->

app/views/site/privacy.html.erb
<h1>Privacy Policy</h1>

<b><%= link_to 'Homepage', root_path %></b>

app/views/site/terms.html.erb
<h1>Terms of Use</h1>

<b><%= link_to 'Homepage', root_path %></b>

app/views/users/index.html.erb
<% @users.each do |user| %>
<p>
<%= user.email %>
</p>
<p>
<%= user.fish %></br>
<%= user.salt %>
</p>
<% end %>

app/views/users/new.html.erb
    <%= form_for @user, {action: user_path(@user)} do |f| %>
      <p><%= f.label :email %> 
      <%= f.text_field :email %>
      </p>
      <p>
       <%= f.label :password %>
      <%= f.text_field :password %>
      </p>
       <p>
       <%= f.label :password_confirmation %>
      <%= f.text_field :password_confirmation %>
      </p>
      <%= f.submit %>
      <% end %>

app/views/users/show.html.erb
This is a show!!!